// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Teste2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void teste2() {
    driver.get("https://igorsmasc.github.io/fomulario_cadastro_selenium/");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Raphael");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Por favor, preencha todos os campos."));
    driver.findElement(By.id("sobrenome")).click();
    driver.findElement(By.id("sobrenome")).sendKeys("Farias");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Por favor, preencha todos os campos."));
    driver.findElement(By.id("masculino")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Por favor, preencha todos os campos."));
    driver.findElement(By.id("java")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Por favor, preencha todos os campos."));
    {
      WebElement dropdown = driver.findElement(By.id("area-interesse"));
      dropdown.findElement(By.xpath("//option[. = 'Backend']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Por favor, preencha todos os campos."));
    driver.findElement(By.id("motivacao")).click();
    {
      WebElement dropdown = driver.findElement(By.id("motivacao"));
      dropdown.findElement(By.xpath("//option[. = 'Backend']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Você preencheu tudo corretamente e é sua última resposta?"));
    driver.switchTo().alert().dismiss();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Você preencheu tudo corretamente e é sua última resposta?"));
    driver.switchTo().alert().dismiss();
    driver.findElement(By.id("java")).click();
    driver.findElement(By.id("selenium")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Você preencheu tudo corretamente e é sua última resposta?"));
    driver.switchTo().alert().dismiss();
    {
      WebElement dropdown = driver.findElement(By.id("area-interesse"));
      dropdown.findElement(By.xpath("//option[. = 'Backend']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Por favor, preencha todos os campos."));
    {
      WebElement dropdown = driver.findElement(By.id("area-interesse"));
      dropdown.findElement(By.xpath("//option[. = 'Testes']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Você preencheu tudo corretamente e é sua última resposta?"));
    driver.switchTo().alert().dismiss();
    driver.findElement(By.id("motivacao")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Você preencheu tudo corretamente e é sua última resposta?"));
    driver.switchTo().alert().accept();
  }
}
