// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Teste1Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void teste1() {
        driver.get("https://igorsmasc.github.io/fomulario_cadastro_selenium//fomulario_cadastro_selenium/");
        driver.findElement(By.id("nome")).click();
        driver.findElement(By.id("nome")).sendKeys("Raphael");
        driver.findElement(By.id("sobrenome")).sendKeys("Farias");
        driver.findElement(By.id("masculino")).click();
        driver.findElement(By.id("java")).click();
        driver.findElement(By.id("selenium")).click();
        driver.findElement(By.id("junit")).click();
        driver.findElement(By.id("javascript")).click();
        {
            WebElement dropdown = driver.findElement(By.id("area-interesse"));
            dropdown.findElement(By.xpath("//option[. = 'Backend']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.id("area-interesse"));
            dropdown.findElement(By.xpath("//option[. = 'Testes']")).click();
        }
        driver.findElement(By.id("motivacao")).click();
        {
            WebElement dropdown = driver.findElement(By.id("motivacao"));
            dropdown.findElement(By.xpath("//option[. = 'Testes']")).click();
        }
        driver.findElement(By.id("porque")).click();
        driver.findElement(By.id("porque")).click();
        driver.findElement(By.id("porque")).click();
        driver.findElement(By.id("porque")).sendKeys("Atualmente estou no último módulo do curso de testes automatizados do Santander Coders,  realizado pela ADA em parceria com o Santander. Um curso que teve duração de 9 meses pois tinha como objetivo formar desenvolvedores capazes de atuar não so na área de testes como também como backend. Nessa vaga poderia por em prática o que foi aprendido no curso e consolidaria minha transição de carreira.");
        driver.findElement(By.id("btn-info")).click();
        assertThat(driver.switchTo().alert().getText(), is("Este formulário é para cadastro de candidatos interessados em vagas de emprego. Por favor, preencha todos os campos obrigatórios e forneça informações precisas e atualizadas. Obrigado!"));
        driver.findElement(By.cssSelector(".btn-primary")).click();
        assertThat(driver.switchTo().alert().getText(), is("Você preencheu tudo corretamente e é sua última resposta?"));
        driver.switchTo().alert().accept();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Raphael"));
        driver.findElement(By.cssSelector("td:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(2)")).getText(), is("Farias"));
        driver.findElement(By.cssSelector("td:nth-child(3)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(3)")).getText(), is("masculino"));
        driver.findElement(By.cssSelector("td:nth-child(4)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(4)")).getText(), is("Backend, Testes"));
        driver.findElement(By.cssSelector("td:nth-child(5)")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(5)")).getText(), is("Testes"));
    }
}
